### ISSUE TITLE
Inconsistent gauges after hot-restart on endpoints /clusters and /stats/prometheus

### ISSUE THREAD

**Issue by andrzejwaw** [envoyproxy/envoy#10806]
*Description*:
After hot-restart, gauges, especially upstream_cx_active on /stats/prometheus endpoint, do not reset themselves. Values from previous instances are added to current. 
Sending POST to /reset_counters does not reset gauges either.

Should envoy behave like this?

It can be easily reproduced by checking /stats/prometheus metrics, before and after hot-restart and comparing them to cx_active returned /clusters admin endpoint

```
curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active
```

*Repro steps*:

* checkout branch hot_restart_container of respository https://github.com/andrzejwaw/envoy/tree/hot_restart_container

* in *envoy/examples/front-proxy* execute 
    ```docker-compose-up```
* send some request to services
    ```
    wrk -t12 -c400 -d30s http://localhost:8000/service/1
    ```
* check metrics:
    ```
    $ curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active' | grep service1
    envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 6
    $ curl http://localhost:8001/clusters 2>/dev/null | grep 'cx_active' | grep service1
    service1::192.168.128.3:80::cx_active::6
    ```
* make a hot-restart (send SIGHUP signal to hot-restarter.py process) and wait for it (up to one minute):
* check metrics:    
    **After hot-restart gauge upstream_cx from /stats/prometheus is inconsistent with cx_active from /clusters endpoint:**

    ```
    $ curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active' | grep service1
    envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 6

    $ curl http://localhost:8001/clusters 2>/dev/null | grep 'cx_active' | grep service1
    service1::192.168.128.3:80::cx_active::0
    ```
    **this makes it difficult to analyze the metrics**

* send more requests
    ```
    wrk -t12 -c400 -d30s http://localhost:8000/service/1
    ```
* check metrics:    
    ```
    $ curl http://localhost:8001/stats/prometheus 2>/dev/null | grep 'upstream_cx_active' | grep service1
    envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 12

    $ curl http://localhost:8001/clusters 2>/dev/null | grep 'cx_active' | grep service1
    service1::192.168.128.3:80::cx_active::6
    ```

I was expecting that after hot-restart both cx_active values from /stats/prometheus endpoint and /clusters endpoint will be equal to 0.

**Comment by mk46** [comment]
Hi @andrzejwaw, 
FYI, Statistics and some locks are kept in a shared memory region which means gauges will be consistent across both processes as restart is taking place. 
If you want to reset the metrics go to the admin page and click on "reset counters".

**Comment by jmarantz** [comment]
Thanks for the report, @andrzejwaw 

@mk46 stats are not kept in shared memory any longer. They are synced via RPC from parent to child during hot-restart.

Gauge behavior depends on how it was declared. The one referenced here is:
```
GAUGE(upstream_cx_active, Accumulate)    
```
which means that it accumulates across a hot-restart. There are also gauges that are declared as NeverImport:
```
GAUGE(membership_total, NeverImport)  
```

`/reset_counters` does not reset gauges. Are you requesting `/reset_gauges`? I'm not sure that makes sense for a Gauge in general, and this one in particular, to be honest.

I'm not totally following your example. Are you saying the gauges are wrong? I'm not an expert on the semantics of `upstream_cx_active`. Is that measuring the L4 connections to an upstream? If that's the case I'd expect the connection to the upstream to be opened in response to an initial downstream request, and to stay open. I'd expect the count representing the sum of parent/child connections to upstreams to be reflected in the child-envoy stat. However, I think I might also expect that as the parent shuts down, it would drop its upstream connections, decrement the gauge, and have that decrement propagate to the child.

I don't know if Envoy has a test for that flow. Is that the issue? I could imagine there could be a bug where the connections to the upstream are shut down but the gauge-decrement is not propagated to the child, but I'm not sure.

**Comment by mk46** [comment]
@jmarant Thanks, I get that from docs and a blog written by @mattklein123 on hot restart. RPC and shared memory both used in parent-child communication. If my understanding is not correct then need to change https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart

**Comment by mattklein123** [comment]
>  If my understanding is not correct then need to change https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart

Yes this page is out of date. Either myself or @jmarantz will fix it. Thank you for bring it to our attention!

**Comment by tony612** [comment]
Looks like this is similar to my this issue https://github.com/envoyproxy/envoy/issues/9070#issuecomment-614427664

**Comment by andrzejwaw** [comment]
Hi, I've updated branch hot_restart_container of respository https://github.com/andrzejwaw/envoy/tree/hot_restart_container 
with added paramters *--parent-shutdown-time-s 15 --drain-time-s 10* and made a script for tests ( */opt/envoy/examples/front-proxy/test.sh* ) 
so more tests can be done easly. Also used netstats to check active connections.

As @jmarantz said
> However, I think I might also expect that as the parent shuts down, it would drop its upstream connections, decrement the gauge, and have that decrement propagate to the child.

I expected also, that after parents shutdown, gauge value will drop, so in example i've set parent shutdown time and drain time.

In pseudo code test looks like:

```
show_metrics
make_some_requests
show_metrics

make_hot_restart
check_envoys_uptime_and_wait_for_parent_to_die
show_metrics

make_some_requests
show_metrics
sleep_seconds

make_hot_restart
check_envoys_uptime_and_wait_for_parent_to_die
show_metrics

```

And last checking of metrics result is:

```
### 04/20/20.09:51:54:168121200: Show metrics ###
/clusters cx-active:
service1::172.21.0.4:80::cx_active::0
/stats/prometheus cx-active:
envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 12
netstat -tup -W:
tcp        0      0 d16c99ec5c1f:39758      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54156      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54012      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54154      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39866      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39762      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39764      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54018      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39760      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54244      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39766      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54230      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
```
So, as we see netstat and clusters show all connection closed, gauge is not.

@mattklein123 I think it is more concerns area/stats then area/docs. The gauge is more inconsistent on every hot-restart. It is hard to relay on that metric, if you do not know that hot-restart was done. 

And here are full details of execution */opt/envoy/examples/front-proxy/test.sh* within envoy container:
```
# bash /opt/envoy/examples/front-proxy/test.sh

### 04/20/20.09:50:47:941460000: Show metrics ###
/clusters cx-active:
service1::172.21.0.4:80::cx_active::0
/stats/prometheus cx-active:
envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 0
netstat -tup -W:

### 04/20/20.09:50:48:001711900: Send some requests ###
Running 10s test @ http://localhost:80/service/1
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   554.77ms  272.50ms   1.57s    67.48%
    Req/Sec    79.98     67.17   310.00     68.62%
  6818 requests in 10.09s, 1.68MB read
  Non-2xx or 3xx responses: 3733
Requests/sec:    676.05
Transfer/sec:    170.77KB

### 04/20/20.09:50:58:377360300: Show metrics ###
/clusters cx-active:
service1::172.21.0.4:80::cx_active::6
/stats/prometheus cx-active:
envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 6
netstat -tup -W:
tcp        0      0 d16c99ec5c1f:39758      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 8/envoy
tcp        0      0 d16c99ec5c1f:39866      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 8/envoy
tcp        0      0 d16c99ec5c1f:39762      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 8/envoy
tcp     2107      0 d16c99ec5c1f:39764      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 8/envoy
tcp        0      0 d16c99ec5c1f:39760      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 8/envoy
tcp        0     39 d16c99ec5c1f:39766      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 8/envoy

### 04/20/20.09:50:58:502086800: making hot-restart, sending sighup to pid: 6 ###

### 04/20/20.09:50:58:510403800: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root         8     7  4 09:48 ?        00:00:07 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 0 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 0,
  "uptime_current_epoch": "168s",
  "uptime_all_epochs": "168s"
}
Parent still exist

04/20/20.09:50:58:544930900 Sleep for 3

### 04/20/20.09:51:01:551883300: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root         8     7  4 09:48 ?        00:00:08 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 0 --parent-shutdown-time-s 15 --drain-time-s 10
root        92    85  3 09:50 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 1,
  "uptime_current_epoch": "3s",
  "uptime_all_epochs": "171s"
}
Parent still exist

04/20/20.09:51:01:582125300 Sleep for 3

### 04/20/20.09:51:04:587994300: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root         8     7  4 09:48 ?        00:00:08 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 0 --parent-shutdown-time-s 15 --drain-time-s 10
root        92    85  2 09:50 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 1,
  "uptime_current_epoch": "6s",
  "uptime_all_epochs": "174s"
}
Parent still exist

04/20/20.09:51:04:618059600 Sleep for 3

### 04/20/20.09:51:07:623789800: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root         8     7  4 09:48 ?        00:00:08 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 0 --parent-shutdown-time-s 15 --drain-time-s 10
root        92    85  1 09:50 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 1,
  "uptime_current_epoch": "9s",
  "uptime_all_epochs": "177s"
}
Parent still exist

04/20/20.09:51:07:651508000 Sleep for 3

### 04/20/20.09:51:10:656398400: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root         8     7  4 09:48 ?        00:00:08 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 0 --parent-shutdown-time-s 15 --drain-time-s 10
root        92    85  1 09:50 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 1,
  "uptime_current_epoch": "12s",
  "uptime_all_epochs": "180s"
}
Parent still exist

04/20/20.09:51:10:680607500 Sleep for 3

### 04/20/20.09:51:13:685911200: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root        92    85  1 09:50 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 1,
  "uptime_current_epoch": "15s",
  "uptime_all_epochs": "183s"
}

### 04/20/20.09:51:13:712590300: Show metrics ###
/clusters cx-active:
service1::172.21.0.4:80::cx_active::0
/stats/prometheus cx-active:
envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 6
netstat -tup -W:
tcp        0      0 d16c99ec5c1f:39758      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39866      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39762      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39764      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39760      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39766      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -

### 04/20/20.09:51:13:760103000: Send some requests ###
Running 10s test @ http://localhost:80/service/1
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   360.33ms  214.69ms   1.02s    71.23%
    Req/Sec    91.88     81.16   420.00     80.17%
  7504 requests in 10.05s, 1.87MB read
  Non-2xx or 3xx responses: 7504
Requests/sec:    746.40
Transfer/sec:    190.15KB

### 04/20/20.09:51:23:892664300: Show metrics ###
/clusters cx-active:
service1::172.21.0.4:80::cx_active::6
/stats/prometheus cx-active:
envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 12
netstat -tup -W:
tcp        0      0 d16c99ec5c1f:39758      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54156      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 92/envoy
tcp        0      0 d16c99ec5c1f:54012      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 92/envoy
tcp        0      0 d16c99ec5c1f:54154      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 92/envoy
tcp        0      0 d16c99ec5c1f:39866      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39762      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39764      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54018      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 92/envoy
tcp        0      0 d16c99ec5c1f:39760      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54244      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 92/envoy
tcp        0      0 d16c99ec5c1f:39766      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54230      front-proxy_service1_1.front-proxy_envoymesh:http ESTABLISHED 92/envoy

04/20/20.09:51:23:972571300 Sleep for 15

### 04/20/20.09:51:38:982699000: making hot-restart, sending sighup to pid: 6 ###

### 04/20/20.09:51:38:989809100: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root        92    85 14 09:50 ?        00:00:06 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 1,
  "uptime_current_epoch": "41s",
  "uptime_all_epochs": "209s"
}
Parent still exist

04/20/20.09:51:39:016859000 Sleep for 3

### 04/20/20.09:51:42:021225400: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root        92    85 13 09:50 ?        00:00:06 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
root       245   238  2 09:51 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 2 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 2,
  "uptime_current_epoch": "3s",
  "uptime_all_epochs": "212s"
}
Parent still exist

04/20/20.09:51:42:052572600 Sleep for 3

### 04/20/20.09:51:45:026936100: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root        92    85 12 09:50 ?        00:00:06 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
root       245   238  1 09:51 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 2 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 2,
  "uptime_current_epoch": "6s",
  "uptime_all_epochs": "215s"
}
Parent still exist

04/20/20.09:51:45:056065700 Sleep for 3

### 04/20/20.09:51:48:063366100: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root        92    85 12 09:50 ?        00:00:06 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
root       245   238  1 09:51 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 2 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 2,
  "uptime_current_epoch": "9s",
  "uptime_all_epochs": "218s"
}
Parent still exist

04/20/20.09:51:48:095245600 Sleep for 3

### 04/20/20.09:51:51:101464800: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root        92    85 11 09:50 ?        00:00:06 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 1 --parent-shutdown-time-s 15 --drain-time-s 10
root       245   238  1 09:51 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 2 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 2,
  "uptime_current_epoch": "12s",
  "uptime_all_epochs": "221s"
}
Parent still exist

04/20/20.09:51:51:135300500 Sleep for 3

### 04/20/20.09:51:54:141039300: Checking envoys exists  ###
UID        PID  PPID  C STIME TTY          TIME CMD
root       245   238  1 09:51 ?        00:00:00 /usr/local/bin/envoy -l debug -c /etc/front-envoy.yaml --service-cluster front-proxy --service-node front-proxy-id --base-id 1 --restart-epoch 2 --parent-shutdown-time-s 15 --drain-time-s 10
{
  "restart_epoch": 2,
  "uptime_current_epoch": "15s",
  "uptime_all_epochs": "224s"
}

### 04/20/20.09:51:54:168121200: Show metrics ###
/clusters cx-active:
service1::172.21.0.4:80::cx_active::0
/stats/prometheus cx-active:
envoy_cluster_upstream_cx_active{envoy_cluster_name="service1"} 12
netstat -tup -W:
tcp        0      0 d16c99ec5c1f:39758      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54156      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54012      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54154      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39866      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39762      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39764      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54018      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39760      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54244      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:39766      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
tcp        0      0 d16c99ec5c1f:54230      front-proxy_service1_1.front-proxy_envoymesh:http TIME_WAIT   -
```

**Comment by mattklein123** [comment]
@andrzejwaw can you please summarize what you think the bug is? Which stat(s) are broken?

@jmarantz I suspect the issue here is that we are missing the final flush before the parent shuts down. This was never a problem previously with shared memory. I wonder if when the parent is actually gone for accumulate gauges we need to actually do a final subtraction or something like that?

**Comment by jmarantz** [comment]
That was my suspicion as well, and I want need to review the 2s complement logic when we are transmitting a decremented gauge.

Do you have a recommendation of what needs to be modified to kick off a final flush?

**Comment by mattklein123** [comment]
> Do you have a recommendation of what needs to be modified to kick off a final flush?

I think there are probably 2 options:
1) See the logic around `sendParentTerminateRequest` and `startParentShutdownSequence`. I think as part of this flow you could do a final stats fetch and update, but TBH I think this will a) be difficult and b) still not catch all the stat decrements.
2) When you know the parent is going away, force decrement any remaining parent gauge deltas on accumulate gauges to reconcile the parent going away. This is what I think we should do.

**Comment by andrzejwaw** [comment]
@mattklein123 I noticed the problem on *upstream_cx_active* and *lb_subsets gauges* from */stats/prometheus*. But probably it affects all accumulate gauges.

Gauge *upstream_cx_active* should report open connections for upstream also after hot-restart, it does not. After hot-restart it holds values from parent (even if parent died). Should drop values after parent shutdown.
Gauge *lb_subsets* - should be constant after each hot-restart. Now, after each restart value is incremented.

**Comment by mattklein123** [comment]
@andrzejwaw thanks, I think we know what the issue is. Hopefully @jmarantz can work on a fix.

**Comment by jmarantz** [comment]
I have started working on this. Doesn't look too hard, except for the integration test :)

**Comment by jmarantz** [comment]
The code, per Matt's option 2 above, was easy enough. But I added some logging to see what was going on in the integration test, and felt like ti was doing the wrong thing. e.g.
```
[2020-05-22 16:43:50.496][844][error][misc] [source/common/stats/stat_merger.cc:147] JOSH: subtracting 2147483647 from gauge server.days_until_first_cert_expiring with current value 2147483647
```
Probably that gauge should be labeled NeverImport; it was likely an oversight to accumulate those.

Another case is:
```
[2020-05-22 16:43:50.497][844][error][misc] [source/common/stats/stat_merger.cc:147] JOSH: subtracting 8388608 from gauge server.memory_heap_size with current value 6291456
```
Probably NeverImport for that too, though I can kind of see why you might think that makes sense to accumulate.

Maybe it should be an ASSERT failure to call set() on a Gauge that's allocated with Accumulate.

Another one is the gauge I added to track `hot_restart_generation`, which uses Accumulate to add values from the parent. I think that will start to fail if I zero out parent contribution, though for some reason hotrestart_test worked for me. I have a feeling I was polling the child value before the parent had exited in the test. I guess we could just use separate logic to track that, though I think implementing that as an imported gauge, as I did, had some test coverage value.

**Comment by jmarantz** [comment]
I think this can largely be a question of refinement at this point. But @mattklein123 could use your opinion on whether this is the right direction. I'm changing a fairly large number of Accumulate stats to NeverImport. Some of them seem fairly obvious that we should never have been importing them. In one case (health check) there was custom logic to defeat sharing across hot-restart parent/child, which I think it was correct to simply remove. In others (connection counts etc) the combined count might be useful, but there were so many calls to Gauge::set() that were violating my new assertion that I had to just switch them to NeverImport.

We could, I guess, leave the ones we think make sense as Accumulate but still call set(), and just remove the assert after having done the audit. But I think any time we are calling Gauge::set() with an Accumulate stat it deserves some scrutiny. WDTY?

**Comment by jmarantz** [comment]
WiP PR here: https://github.com/envoyproxy/envoy/pull/11301
