### ISSUE TITLE
docker linux multiarch ci test fails randomly

### ISSUE THREAD

**Issue by qinggniq** [envoyproxy/envoy#14971]
*Title*: *docker linux multiarch ci test fails randomly*
Hello, the ci always failed at envoy-presubmit (docker linux multiarch), it always failed at the same location:
```
2021-02-05T09:04:56.3211096Z Dockerfile-envoy:7
2021-02-05T09:04:56.3211650Z --------------------
2021-02-05T09:04:56.3212144Z    6 |     
2021-02-05T09:04:56.3212793Z    7 | >>> RUN echo "d6c40440609a23483f12eb6295b5191e94baf08298a856bab6e15b10c3b82891  /tmp/su-exec.c" > /tmp/checksum \
2021-02-05T09:04:56.3216247Z    8 | >>>     && curl -o /tmp/su-exec.c https://raw.githubusercontent.com/ncopa/su-exec/212b75144bbc06722fbd7661f651390dc47a43d1/su-exec.c \
2021-02-05T09:04:56.3217503Z    9 | >>>     && sha256sum -c /tmp/checksum \
2021-02-05T09:04:56.3218139Z   10 | >>>     && gcc -Wall /tmp/su-exec.c -o/usr/local/bin/su-exec \
2021-02-05T09:04:56.3219070Z   11 | >>>     && chown root:root /usr/local/bin/su-exec \
2021-02-05T09:04:56.3220130Z   12 | >>>     && chmod 0755 /usr/local/bin/su-exec
2021-02-05T09:04:56.3220697Z   13 |     
2021-02-05T09:04:56.3221440Z --------------------
2021-02-05T09:04:56.3223669Z error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c echo "d6c40440609a23483f12eb6295b5191e94baf08298a856bab6e15b10c3b82891  /tmp/su-exec.c" > /tmp/checksum     && curl -o /tmp/su-exec.c https://raw.githubusercontent.com/ncopa/su-exec/212b75144bbc06722fbd7661f651390dc47a43d1/su-exec.c     && sha256sum -c /tmp/checksum     && gcc -Wall /tmp/su-exec.c -o/usr/local/bin/su-exec     && chown root:root /usr/local/bin/su-exec     && chmod 0755 /usr/local/bin/su-exec]: exit code: 1
2021-02-05T09:04:56.3473556Z ##[error]Bash exited with code '1'.
```
the failure appeared at some prs:
pr https://github.com/envoyproxy/envoy/pull/14895
pipelines https://github.com/envoyproxy/envoy/pull/14895/checks?check_run_id=1809760617
pr https://github.com/envoyproxy/envoy/pull/14945
pipelines https://github.com/envoyproxy/envoy/pull/14945/checks?check_run_id=1833532266
pr https://github.com/envoyproxy/envoy/pull/14810
pipelines https://github.com/envoyproxy/envoy/runs/1837543464

some links about the  rpc error: code = Unknown desc :

https://github.com/docker/buildx/issues/101
https://stackoverflow.com/questions/59868448/rpc-error-code-unknown-desc-failed-to-build-llb (edited) 

I founded it in my [pr](https://github.com/envoyproxy/envoy/pull/14810) yesterday, today this ci test passed in new commit. It appears randomly.

**Comment by phlax** [comment]
from my reading of those links it seems like it may be running out of mem.

if it is the same issue, then it seems like running it a second time should fix the problem, but it would be good to know what is the actual cause  and deal with that

**Comment by aemperador** [comment]
hi, I work with ppc64-le. I will be looking into this

**Comment by antoniovicente** [comment]
cc @lizan

**Comment by antoniovicente** [comment]
@envoyproxy/maintainers

**Comment by mattklein123** [comment]
I think we fixed the su-exec issue. Let's track other problems in fresh issues.

**Comment by phlax** [comment]
i think the issue highlighted here is the common failure - i havent seen the su-exec issue too often - and i see this one regularly

essentially i think we need more memory in the docker build container - but maybe wrong

**Comment by phlax** [comment]
i guess if the problem goes away now we can ignore

**Comment by phlax** [comment]
@mattklein123 afaict the problem remains:

https://dev.azure.com/cncf/envoy/_build/results?buildId=68549&view=logs&j=2229703b-209a-5c70-43aa-3eacf674f12a&t=06218374-b1ef-5f45-4455-5a78d6d63b65&l=361

i dont think that su-exec was ~ever the issue - i think it was the mem issue pointed to here

at very least the flake remains and i think this ticket should still be active

**Comment by alyssawilk** [comment]
Looks like it's failing to install ca-certificates, presumably the same network flakes that caused su-exec work to fail.

Probably a stupid question but why can't we have these things preloaded on the image?

**Comment by phlax** [comment]
i might be wrong but i think this is the symptom not the cause

either way - the build stage is no longer required so im not sure why its doing this at all - ill PR...

**Comment by mattklein123** [comment]
OK sorry yes let's keep it opening if it's still failing. @phlax you have quite a bit of understanding of all of this now. Can you take a look as well and do whatever PRs you think are necessary? Thank you.

**Comment by antoniovicente** [comment]
CI for https://github.com/envoyproxy/envoy/pull/15297 shows a breakage upgrading libzstd1:

2021-03-09T00:30:56.8838753Z #8 25.70 The following packages will be upgraded:
2021-03-09T00:30:57.0337701Z #8 25.70   libzstd1
2021-03-09T00:30:57.3012219Z #8 26.12 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2021-03-09T00:30:57.3013565Z #8 26.12 Need to get 161 kB of archives.
2021-03-09T00:30:57.3014418Z #8 26.12 After this operation, 0 B of additional disk space will be used.
2021-03-09T00:30:57.3016408Z #8 26.12 Get:1 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 libzstd1 arm64 1.3.3+dfsg-2ubuntu1.2 [161 kB]
2021-03-09T00:30:58.5018762Z #8 27.22 debconf: delaying package configuration, since apt-utils is not installed
2021-03-09T00:30:58.6518775Z #8 27.33 Fetched 161 kB in 1s (223 kB/s)
2021-03-09T00:30:58.6520804Z #8 27.39 Error while loading /usr/local/sbin/dpkg-split: No such file or directory
2021-03-09T00:30:58.6521834Z #8 27.39 Error while loading /usr/local/sbin/dpkg-deb: No such file or directory
2021-03-09T00:30:58.6523380Z #8 27.40 dpkg: error processing archive /var/cache/apt/archives/libzstd1_1.3.3+dfsg-2ubuntu1.2_arm64.deb (--unpack):
2021-03-09T00:30:58.6524413Z #8 27.40  dpkg-deb --control subprocess returned error exit status 1
2021-03-09T00:30:58.6525115Z #8 27.40 Errors were encountered while processing:
2021-03-09T00:30:58.6525976Z #8 27.41  /var/cache/apt/archives/libzstd1_1.3.3+dfsg-2ubuntu1.2_arm64.deb

**Comment by phlax** [comment]
@arkodg seems like your fix worked! nice one
