### ISSUE TITLE
Cannot chown `/dev/stdout` in Cloud Run

### ISSUE THREAD

**Issue by paymog** [envoyproxy/envoy#17568]
*Title*:  Cannot chown `/dev/stdout` in Cloud Run

*Description*:
I'm trying to run envoy in Google Cloud Run but the container immediately fails with 

```
chown: /dev/stdout: Operation not permitted
chown: /dev/stderr: Operation not permitted
```

I've tried running the following docker images all with the same result: `envoy-alpine:1.{16,17,19}.0` and `envoy-alpine-dev:0bd670a2c0851cb5d0a21acbb89501afe976f455`.

*Repro steps*:
1. create gcp project
2. create dockerfile with a single `FROM envoyproxy/envoy-alpine:v1.19.0`
3. `gcloud builds submit --tag gcr.io/$PROJECT/envoy && gcloud run deploy envoy --image gcr.io/$PROJECT/envoy  --platform=managed --region=us-east4`
4. see the error in the gcloud logs

**Comment by daixiang0** [comment]
like #11551

ping @phlax

**Comment by hds** [comment]
In case this helps someone, we've seen this issue appear just after the Kubelets in our k8s cluster were upgraded from 1.19 to 1.20.

On another cluster where the Kubelets have yet to be updated, the issue doesn't occur - using the exact same version of envoy (1.18.2 with the envoy-alpine image).

Perhaps some special protection has been added to those devices in that version?

**Comment by phlax** [comment]
> upgraded from 1.19 to 1.20.

this seems odd, the problem should have been fixed some time ago, not sure why this is resurfacing

> with the envoy-alpine image

i think the alpine image is kinda deprecated - i would suggest using the distroless image - apart from anything the distroless image does not require any permission mangling

**Comment by hds** [comment]
Do you know what the issue is that should have been fixed?

**Comment by phlax** [comment]
the fix was in this PR https://github.com/envoyproxy/envoy/pull/15115/files

not sure which versions it has been backported to - i know it was backported to at least one version

**Comment by hds** [comment]
The fix that was mentioned above (https://github.com/envoyproxy/envoy/pull/15115/files) has been backported to 18.2 (which is the version we were initially using), but doesn't fix the problem for us when running on Kubernetes with Kubelet version 1.20.

The following 2 solutions **did** fix the issue. Only one of these needed to be applied in our case:

1. Setting `securityContext.runAsUser = 1000` and `securityContext.runAsGroup = 1000` for the Envoy container in the deployment spec.
2. Switching to the `envoy-distroless` image instead of `envoy-alpine` that we were previously using (recommended by @phlax - Thank you!)
