### ISSUE TITLE
Wildcard Let's Encrypt certs do not validate after DST Root CA expiration

### ISSUE THREAD

**Issue by travisgroth** [envoyproxy/envoy#18510]
*Title*: Wildcard Let's Encrypt certs do not validate after [DST Root CA expiration](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

*Description*:
After one of the original Let's Encrypt CAs expired, wildcard certs issued by LE no longer validate with envoy.  I am not able to personally reproduce with non-wildcards.

I believe this is due to [boringssl behavior](https://bugs.chromium.org/p/boringssl/issues/detail?id=439), though I'd expect all LE certs have this problem in that case.

*Repro steps*:

To make a self contained reproduction, I've created an envoy configuration with an `http` listener (http://localhost:10000) that proxies to a local `https` listener (https://test-upstream.letsencrypt.localhost.pomerium.io:10443) that proxies the request to httpbin.org.  The `https` listener is using a wildcard let's encrypt cert.

1. Download [gist](https://gist.github.com/travisgroth/625f0adcff0e1e34b1a2afbeb54f11ea).  The included certificates were generated for this repro and not used anywhere.
2. Run with `envoy -c config.yaml`
3. Verify system curl sees `https://test-upstream.letsencrypt.localhost.pomerium.io:10443` as valid:
```bash
curl -I https://test-upstream.letsencrypt.localhost.pomerium.io:10443
HTTP/1.1 200 OK
date: Thu, 07 Oct 2021 20:56:19 GMT
content-type: text/html; charset=utf-8
content-length: 9593
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 21
```
4. Curl through envoy
```bash
curl localhost:10000
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

You'll note `curl` has no issue but envoy itself does.  

*Admin and Stats Output*:
n/a

*Config*:

```yaml
#
# http://localhost:10000 -> [envoy] -> https://test-upstream.letsencrypt.localhost.pomerium.io:10443 -> [envoy] -> https://httpbin.org
#
# be sure to uncomment your operating system's cert store.

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: http
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                route_config:
                  name: test_upstream
                  virtual_hosts:
                    - name: test_upstream
                      domains: ["*"]
                      routes:
                        - match: 
                            prefix: "/"
                          route:
                            cluster: test_upstream
                            auto_host_rewrite: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    - name: https-upstream
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: upstream_https
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                route_config:
                  name: httpbin.org
                  virtual_hosts:
                    - name: httpbin.org
                      domains: ["*"]
                      routes:
                        - match: 
                            prefix: "/"
                          route:
                            cluster: httpbin.org
                            auto_host_rewrite: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  certificate_chain: 
                    filename: ./fullchain.pem
                  private_key:
                    filename: ./privkey.pem

  clusters:
    - name: test_upstream
      connect_timeout: 1s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: /etc/ssl/cert.pem # osx
                # filename: /etc/ssl/certs/ca-certificates.crt # linux
      load_assignment:
        cluster_name: test_upstream
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: test-upstream.letsencrypt.localhost.pomerium.io
                      port_value: 10443

    - name: httpbin.org
      connect_timeout: 1s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
      load_assignment:
        cluster_name: test_upstream
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbin.org
                      port_value: 443


```

*Logs*:
```
[2021-10-07T20:49:18.754Z] "GET / HTTP/1.1" 503 UF 0 195 2 - "-" "curl/7.79.0" "7889b267-29b4-4680-930f-f20807690799" "localhost:10000" "127.0.0.1:10443"
[2021-10-07 16:48:39.667][12679903][debug][pool] [source/common/conn_pool/conn_pool_base.cc:407] [C1] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2021-10-07 16:48:39.667][12679903][debug][router] [source/common/router/router.cc:1075] [C0][S10352822734306019930] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2021-10-07 16:48:39.668][12679903][debug][http] [source/common/http/filter_manager.cc:935] [C0][S10352822734306019930] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}
```

**Comment by phlax** [comment]
i think i understand the related boringssl issue - but also hoping that the certs are being updated to remove the expired one in distros etc

**Comment by travisgroth** [comment]
@phlax the way the trust chain is built and evaluated is the problem.  On the same system, other tools (such as curl) work fine with the expired CA present.  

You can see some discussion in the [boringssl thread](https://bugs.chromium.org/p/boringssl/issues/detail?id=439) about the behavior.  I'm not sure if just pulling in the fix from Boring is sufficient but I'd expect the behavior to be to follow the shortest CA chain and validate that.  What's happening now is the longer of two trust chains is being followed and the root of it is expired, even though a shorter (and also trusted) root is present.

(you updated as I was responding)

Yes, the expired root cert will likely get removed over time but a fix within envoy/boring would be dramatically more timely.  Since _most_ software isn't impacted, I don't think operating system vendors have a lot of pressure to remove the old CA.  Openssl, for instance, has the shorter chain evaluation behavior.  

If envoy doesn't address this, folks will likely need to rebuild their system trust stores when deploying envoy outside of the official container, which doesn't scale well and will lead to a lot of user frustration.

**Comment by phlax** [comment]
yep, understood ive raised it with other maintainers - backporting to old versions is non-trivial - but as you say may well be necessary

**Comment by travisgroth** [comment]
Great thanks @phlax 👍 .

**Comment by yegle** [comment]
FWIW, Ubuntu already blacklisted the expired certificate (https://launchpad.net/ubuntu/+source/ca-certificates/20210119~18.04.2).

**Comment by wrflemin** [comment]
> hi @travisgroth thanks for reporting this
> 
> im assuming that you are running with the `envoyproxy/envoy` docker image - is that correct ?
> 
> could you also let us know which version you are using (im hoping that the v1.20-latest image may have escaped this problem)

I can confirm the offending cert still exists in v1.20.0 docker image. Will there be new images built without that certificate, or an idea of when 1.21 is coming (presumably without this cert)? Right now we are building the following to work around the issue:
```
FROM envoyproxy/envoy:v1.20.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates
```

**Comment by travisgroth** [comment]
Still an issue

**Comment by ggreenway** [comment]
As I understand it, the issue doesn't have anything to do with which CA certs are in the OS or docker image, it has to do with cross-signed certs with one of the CAs being expired. Correct?

@davidben It sounds like if Envoy sets `X509_V_FLAG_TRUSTED_FIRST` this should be resolved. Is that correct? What are the chances that setting that flag will break some other valid certificate chain is currently working?

**Comment by ggreenway** [comment]
@travisgroth if you want to help with a fix, any chance you can figure out how to add a new (self signed) cert to https://github.com/envoyproxy/envoy/blob/main/test/extensions/transport_sockets/tls/test_data/certs.sh that is valid but fails validation due to this bug?

**Comment by davidben** [comment]
BoringSSL flipped the default already.
https://boringssl.googlesource.com/boringssl/+/8f5eb80b810ff63d14ad3535cb16f7cb8271a4f5

Also it whether it may break other stuff, you'll just have to try it and see I'm afraid. The legacy verifier you're using doesn't have a real path builder. Trusted first merely changes it from one arbitrary decision to the other. It's possible to construct inputs that require it enabled, ones that require it disabled, and ones that don't work with either.

I think, on balance, it is better to have it enabled, since we know Let's Encrypt works better with it, and it matches what OpenSSL upstream does. But I can't give you anything beyond that. We don't use this code in Chrome and will be replacing it more broadly. The replacement won't look like this stack at all and will look closer to PR #10621. (Many of the problems with this stack, are, alas, part of the public API. I have hopes to _eventually_ align behaviors and make this API a shim over the old one, but that's very speculative and may not even be feasible. It certainly has no future as the preferred API.)

**Comment by linnea-s** [comment]
I believe this is still an issue, and does not only affect wildcard certificates. I believe I hit the same issue using TLS termination in istio towards a site using a certificate signed by letsencrypt. I condensed it to a small testcase. With the below config, `curl http://localhost:10000` yields `stream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`. The log says:
```
[2022-02-25 14:11:55.027][15][debug][connection] [source/extensions/transport_sockets/tls/cert_validator/default_validator.cc:202] X509_verify_cert: certificate verification error at depth 3: certificate has expired
[2022-02-25 14:11:55.027][15][trace][connection] [source/extensions/transport_sockets/tls/ssl_handshaker.cc:52] [C3] ssl error occurred while read: SSL
[2022-02-25 14:11:55.027][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C3] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[2022-02-25 14:11:55.027][15][debug][connection] [source/common/network/connection_impl.cc:249] [C3] closing socket: 0
[2022-02-25 14:11:55.027][15][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:225] [C3] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

Config:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: letsencrypt.org
                  cluster: letsencrypt.org
  clusters:
  - name: letsencrypt.org
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: letsencrypt.org
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: letsencrypt.org
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: letsencrypt.org
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
            match_typed_subject_alt_names:
            - san_type: DNS
              matcher:
                exact: letsencrypt.org
```

**Comment by ggreenway** [comment]
The BoringSSL version was recently updated in Envoy, and I believe the new version should work for this case. Can someone validate against main?

**Comment by linnea-s** [comment]
> The BoringSSL version was recently updated in Envoy, and I believe the new version should work for this case. Can someone validate against main?

I can confirm that it works in main. I downloaded the docker-distroless artifact from the last complete successful build and loaded it with "docker load" and added a new service to my test above `docker-compose.yml` which is the exact same except exposing envoy on port 10001. `curl http://localhost:10000` (1.21-latest) yields a CERTIFICATE_VERIFY_FAILED error. `curl http://localhost:10001` ([20220321.5](https://dev.azure.com/cncf/envoy/_build/results?buildId=104265)) successfully returns the index page of letsencrypt.org.
