### ISSUE TITLE
envoy-[main,1.27]: ORIGINAL_DST cluster with TLS transport, crash in config validation mode

### ISSUE THREAD

**Issue by pgeler** [envoyproxy/envoy#29423]
this issue cleared through security group and was advised to create a public one:

issue introduced as part of the 1.27 release and was working on the almost the same configuration since 1.18.

simplest way to reproduce it is to define HTTP upstream cluster with TLS upstream like follow:
```
...
  - name: app_cluster
    alt_stat_name: app
    type: ORIGINAL_DST
    lb_policy: CLUSTER_PROVIDED
    original_dst_lb_config:
      use_http_header: true
      http_header_name: x-dst-host
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        common_http_protocol_options:
          max_requests_per_connection: 1
        explicit_http_config:
          http_protocol_options:
            allow_chunked_length: true
            override_stream_error_on_invalid_http_message: false
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_params:
            tls_minimum_protocol_version: TLSv1_2
            tls_maximum_protocol_version: TLSv1_3
```

run envoy in validation mode:  envoy --mode validate -c envoy.yaml

following stack trace exposed:
```
14:27:50  #16 0.444 [2023-08-31 18:27:50.332][10][critical][backtrace] [external/envoy/source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x0
14:27:50  #16 0.444 [2023-08-31 18:27:50.332][10][critical][backtrace] [external/envoy/source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
14:27:50  #16 0.444 [2023-08-31 18:27:50.332][10][critical][backtrace] [external/envoy/source/server/backtrace.h:92] Envoy version: cc3dc27c51404f2f524893eba8a87316d76ab059/1.27.1-dev/Modified/RELEASE/BoringSSL
14:27:50  #16 0.444 [2023-08-31 18:27:50.332][10][critical][backtrace] [external/envoy/source/server/backtrace.h:98] #0: [0x7ff706922520]
14:27:50  #16 0.455 [2023-08-31 18:27:50.342][10][critical][backtrace] [external/envoy/source/server/backtrace.h:96] #1: Envoy::Extensions::TransportSockets::Tls::ClientSslSocketFactory::~ClientSslSocketFactory() [0x558683ecfb35]
14:27:50  #16 0.465 [2023-08-31 18:27:50.352][10][critical][backtrace] [external/envoy/source/server/backtrace.h:96] #2: 
...
```

**Comment by phlax** [comment]
@pgeler if the issue is still present on `main` please target that branch first and then we can look at backports from there

/backport

**Comment by pgeler** [comment]
@phlax I'm going to setup main image build on our end, but no promise, as my previous experience with main was not very pleasant

**Comment by pgeler** [comment]
technically problem is solved in main and 1.28, so if there is no appetite to backport it, to me issue can be closed 🤔

**Comment by phlax** [comment]
@pgeler ill close for now and we can consider backporting if anyone reports an issue

**Comment by michalmiddleton** [comment]
Not sure if me alone is enough to ask for a backport to 1.27.x but I came here with the same problem. 
I'd be ok skipping 1.27.x altogether and going to 1.28 but for some entirely different reason, envoy is crashing with `panic: not implemented` (possibly related to this [open issue](https://github.com/envoyproxy/envoy/issues/31036))

**Comment by michalmiddleton** [comment]
@phlax Not sure if me alone is enough to ask for a backport to 1.27.x but I came here with the same problem. 
I'd be ok skipping 1.27.x altogether and going to 1.28 but for some entirely different reason, envoy is crashing with `panic: not implemented` (possibly related to this [open issue](https://github.com/envoyproxy/envoy/issues/31036))

**Comment by phlax** [comment]
@michalmiddleton scanning above i think it looks like something that should be backported

would you be up for raising a PR ?

i can follow up if not 

/backport

**Comment by michalmiddleton** [comment]
@phlax I wish I could help but this project is way outside of my skills :(

**Comment by phlax** [comment]
np - ill take a look tomorrow

**Comment by phlax** [comment]
@pgeler any ideas when this was fixed on `main` ?

**Comment by pgeler** [comment]
@phlax I believe, I saw commit back then which bring 🔔  and it must be [this one]( https://github.com/envoyproxy/envoy/commit/287a42ff225482596f6e32f6688dc3db7f458023). But did not verify for the fact.

**Comment by pgeler** [comment]
@michalmiddleton for us 1.28.x was only good at exactly at 1.28.0 revision, there number of issues after in release/v1.28 branch, so we lock ourselves on 1.28.0 revision.

**Comment by phlax** [comment]
hmm - that looks like a bit more than we want to backport generally

what issues do you have with 1.28 ? are they resolved in 1.29/main ?

**Comment by michalmiddleton** [comment]
Hi @phlax Looks like I got myself into a bit of situation. I'm blocked from upgrading to any of the next 3 minor releases lol. 

The issue I hit in 1.28 is related to UDP listener (which we use for DNS) https://github.com/envoyproxy/envoy/issues/31036

I haven't been able to compile 1.29 at all because there was a change to the builder image that I'm having hard time replicating in my build environment based on RHEL8 (for FIPS).

**Comment by michalmiddleton** [comment]
Hi @phlax is there anything I can provide to help with this issue? As it turns out, 1.26.x is the last branch that works for us.. and EOL for 1.26 is coming up in 2 months. Thank you

**Comment by michalmiddleton** [comment]
Hi @phlax , I tested this on main/HEAD and the issue is persists. I am starting to be a bit worried about what to do if 1.26 goes EOL and this issue is not fixed :( 
Any help would be greatly appreciated!

**Comment by phlax** [comment]
@michalmiddleton not sure how i can help exactly - rereading above posts and my overriding thought is that issues with more recent releases are higher priority

the issue you posted above https://github.com/envoyproxy/envoy/issues/31036 shoudl be fixed in the latest 1.28 release 

@pgeler its important that you are able to upgrade patch versions as they often bring security patches - in general they should not break things - would be good to understand what changed/broke on `release/v1.28` for you

**Comment by pgeler** [comment]
@phlax my understanding issue was coming form http2 upgrade or something #30882, unfortunately it seem it was ignored

**Comment by michalmiddleton** [comment]
@phlax and @pgeler, I am affected by this issue up to the current dev 1.30. Previously, I mentioned that 1.28 was buggy for a different reason, and I hadn't been able to build or test 1.29 or newer. However, I need to update my statement.

Regarding 1.28: The issue (https://github.com/envoyproxy/envoy/issues/31036) indeed prevented me from using 1.28, but it turns out that 1.28 contains both bugs, and 31036 was just one of the issues that occurred earlier in the code path.

Regarding 1.29 and 1.30-dev: I managed to both build and test them using the official Docker builds of Envoy. Unfortunately, both versions still suffer from this issue.

I will proceed to test whether it's solely the validation mode that crashes or if it affects full Envoy execution as well. Currently, about 30% of our configurations are impacted, and I would very much like to retain config validation if at all feasible.

**Comment by phlax** [comment]
> Regarding 1.29 and 1.30-dev ... both versions still suffer from this issue ... I would very much like to retain config validation if at all feasible.

im not sure im following at this point - my understanding was that this was fixed on `main`

**Comment by michalmiddleton** [comment]
@phlax It was not. 

Here is an example:
```
bash-4.4$ envoy --allow-unknown-static-fields --mode validate -c /mnt/integration.yaml
[2024-02-28 16:24:02.081][22][info][main] [source/server/server.cc:859] runtime: layers:
  - name: static_layer
    static_layer:
      overload:
        global_downstream_max_connections: 50000
[2024-02-28 16:24:02.088][22][info][config] [source/server/configuration_impl.cc:164] loading tracing configuration
[2024-02-28 16:24:02.088][22][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2024-02-28 16:24:02.088][22][info][config] [source/server/configuration_impl.cc:130] loading 1 cluster(s)
[2024-02-28 16:24:02.102][22][warning][tap] [source/extensions/common/tap/admin.cc:36] Admin tapping (via /tap) is unreliable when the admin endpoint is a pipe and the connection is HTTP/1. Either use an IP address or connect using HTTP/2.
[2024-02-28 16:24:02.114][22][info][config] [source/server/configuration_impl.cc:134] loading 0 listener(s)
[2024-02-28 16:24:02.115][22][info][config] [source/server/configuration_impl.cc:150] loading stats configuration
configuration '/mnt/integration.yaml' OK
[2024-02-28 16:24:02.121][22][critical][backtrace] [./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x176e3f8c4720
[2024-02-28 16:24:02.121][22][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2024-02-28 16:24:02.121][22][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 9a47bc9eff9c3283fbfaed9144313b7bda366aac/1.30.0-dev/Modified/RELEASE/BoringSSL
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7ffffec2ecf0]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #1: [0x5555576daf74]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #2: [0x5555576d9f4a]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #3: [0x555558b20989]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #4: [0x555558ae5913]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #5: [0x555558ae6145]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #6: [0x555558edb364]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #7: [0x5555586d2afe]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #8: [0x5555586c376d]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #9: [0x5555586c3320]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #10: [0x5555586945c5]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #11: [0x555558694da6]
[2024-02-28 16:24:02.123][22][critical][backtrace] [./source/server/backtrace.h:98] #12: [0x555556cfd14c]
[2024-02-28 16:24:02.124][22][critical][backtrace] [./source/server/backtrace.h:96] #13: __libc_start_main [0x7ffffe891d85]
Segmentation fault
bash-4.4$
bash-4.4$ envoy --version

envoy  version: 9a47bc9eff9c3283fbfaed9144313b7bda366aac/1.30.0-dev/Modified/RELEASE/BoringSSL

bash-4.4$
```

`integration.yaml`:
```yaml
admin:
  address:
    pipe:
      path: '@/admin'
enable_dispatcher_stats: true
layered_runtime:
  layers:
  - name: static_layer
    static_layer:
      overload:
        global_downstream_max_connections: 50000
node:
  cluster: integration
  id: localhost
  locality:
    region: integration
    zone: one
  metadata:
    application: integration
    version: 1.1.1
  user_agent_name: service-mesh
  user_agent_version: 1.0.0
static_resources:
  clusters:
  - connect_timeout: 5s
    lb_policy: CLUSTER_PROVIDED
    name: s3-bucket-vpc
    transport_socket:
      name: envoy.transport_sockets.tap
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tap.v3.Tap
        common_config:
          admin_config:
            config_id: cluster_s3-bucket-vpc
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            allow_renegotiation: true
    type: ORIGINAL_DST
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
        upstream_http_protocol_options:
          auto_sni: true
```

**Comment by phlax** [comment]
k - im kinda confused in that case i was going on what @pgeler said ...

> technically problem is solved in main and 1.28, so if there is no appetite to backport it, to me issue can be closed 🤔

@michalmiddleton if that is not the case then someone needs to look at fixing this on `main` first

**Comment by michalmiddleton** [comment]
I am not sure why pgeler had better luck either.

How can I move this issue to main? Should I open a new Issue on this?

**Comment by michalmiddleton** [comment]
I am not sure why pgeler had better luck either.

@phlax How can I move this issue to main? Should I open a new Issue on this?

**Comment by phlax** [comment]
> How can I move this issue to main? Should I open a new Issue on this

if you can confirm 100% the problem exists on `main` then its a case of figuring out the fix

im not a c++ dev so have limited to offer in resolving - but from my limited understanding this should be a relatively easy fix if its just an issue with validation code

**Comment by michalmiddleton** [comment]
Yes, the output I posed 40 min ago is from `main` two days ago. Ok I'll create a new issue.
I also tried running that config in normal more (not config validation mode) and it seems to work. So yes, I am hoping it will be a simple fix.

**Comment by phlax** [comment]
no need for a new issue i think - this issue was raised against main

**Comment by michalmiddleton** [comment]
ok. Any idea how can I solicit some help from a c++ dev to take a look?

**Comment by michalmiddleton** [comment]
Hi @kyessenov @lizan I'd really appreciate your help here. 1.26 is about to become unsupported in a few weeks.
Thank you
