### ISSUE TITLE
`//test/integration:tcp_tunneling_integration_test` is extremely flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#39856]
This has been flakey a long time - but it appears it just got a **lot** worse

afaict its failing across the board on tests - but it seems particularly bad for san tests

Its not hard to trigger locally and seems related to https://github.com/envoyproxy/envoy/commit/dbd0cad19aac2b43ea0e8c47b7c3889252603b2f

```console
[ RUN      ] HttpAndIpVersions/ConnectTerminationIntegrationTest.UpstreamClose/IPv4_Http3Downstream_HttpUpstreamHttpParserNghttp2Legacy
test/integration/tcp_tunneling_integration_test.cc:325: Failure
Value of: response_->waitForReset()
  Actual: false (Stream finished while waiting for reset
IntegrationStreamDecoder state:
  saw_end_stream_=1
  saw_reset_=0
  headers_=':status', '200'
'date', 'Thu, 12 Jun 2025 08:25:06 GMT'
'server', 'envoy'

  continue_headers_=null
  body_=there!
  trailers_=null)
Expected: true
Stack trace:
  0x56173b604cb1: Envoy::(anonymous namespace)::ConnectTerminationIntegrationTest_UpstreamClose_Test::TestBody()
  0x5617436a0d6d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x56174366972b: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x561743644b19: testing::Test::Run()
  0x56174364594d: testing::TestInfo::Run()
... Google Test internal frames ...

test/integration/http_integration.cc:385: Failure
Expected equality of these values:
  codec_client_->numActiveRequests()
    Which is: 1
  0
test requires explicit cleanupUpstreamAndDownstream
Stack trace:
  0x56173b85cf00: Envoy::HttpIntegrationTest::~HttpIntegrationTest()
  0x56173b6dbf6e: Envoy::HttpProtocolIntegrationTest::~HttpProtocolIntegrationTest()
  0x56173b5f5b1a: Envoy::(anonymous namespace)::ConnectTerminationIntegrationTest::~ConnectTerminationIntegrationTest()
  0x56173b604776: Envoy::(anonymous namespace)::ConnectTerminationIntegrationTest_UpstreamClose_Test::~ConnectTerminationIntegrationTest_UpstreamClose_Test()
  0x56173b6047ba: Envoy::(anonymous namespace)::ConnectTerminationIntegrationTest_UpstreamClose_Test::~ConnectTerminationIntegrationTest_UpstreamClose_Test()
  0x56174366a212: testing::Test::DeleteSelf_()

```

**Comment by phlax** [comment]
cc @ravenblackx

**Comment by ravenblackx** [comment]
Ah, yeah, there were a bunch of these in the PR as well - these are cases where the test was wrong all along (calling `waitForReset` while not actually expecting a reset; that function which was supposed to be verifying that a reset happened in fact did not verify that, but now does.)

So if any more of these come up, they can *probably* just be replaced with `waitForAnyTermination`.

And then the second error is probably the old pre-existing flakiness, which might be fixed by following the instruction from the error (adding `cleanupUpstreamAndDownstream()` at the end of the test).

I'll do it for this one, but I hope this description makes it something anyone else can also easily do if there are more cases.

**Comment by phlax** [comment]
fixed in #39875

**Comment by phlax** [comment]
it looks like this isnt fixed - its failing pretty frequently

https://github.com/envoyproxy/envoy/actions/runs/19932640369/job/57148611955#step:20:1338

https://github.com/envoyproxy/envoy/actions/runs/19939392749/job/57172970688#step:20:1286

https://github.com/envoyproxy/envoy/actions/runs/19942275183/job/57182893149#step:20:1177

**Comment by phlax** [comment]
https://github.com/envoyproxy/envoy/actions/runs/20084391694/job/57618583853#step:21:1864

**Comment by ravenblackx** [comment]
This looks like a different error than the previous case, the one at the top of the thread was `saw_end_stream_=1` and `test requires explicit cleanupUpstreamAndDownstream`, and this one is neither of those
```
[ RUN      ] HttpAndIpVersions/ConnectTerminationIntegrationTest.EarlyConnectDataRejectedWithOverride/IPv4_HttpDownstream_HttpUpstreamNghttp2Legacy
test/integration/tcp_tunneling_integration_test.cc:468: Failure
Expected equality of these values:
  response_->headers().getStatusValue()
    Which is: "200"
  "400"
    Which is: 0x55f1047e1c92
Stack trace:
  0x55f105db8936: Envoy::(anonymous namespace)::ConnectTerminationIntegrationTest_EarlyConnectDataRejectedWithOverride_Test::TestBody()
  0x55f10e236523: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x55f10e1de4d1: testing::Test::Run()
  0x55f10e1e0d8d: testing::TestInfo::Run()
... Google Test internal frames ...

test/integration/tcp_tunneling_integration_test.cc:469: Failure
Value of: response_->waitForEndStream()
  Actual: false (Timed out (30000ms) waiting for end stream
IntegrationStreamDecoder state:
  saw_end_stream_=0
  saw_reset_=0
  headers_=':status', '200'
'date', 'Wed, 10 Dec 2025 02:03:42 GMT'
'server', 'envoy'

  continue_headers_=null
  body_=
  trailers_=null)
Expected: true
```

It's fine to reuse the issue, but it's not related to the original, and not "isn't fixed" but rather "there is still another flake" or more likely "there is a new flake," and it needs someone else to look at it.

**Comment by ravenblackx** [comment]
The failing test was composed 2025-11-06 and added 7 days ago [here](https://github.com/envoyproxy/envoy/commit/0f485ec2e6fa3a1ece2ad420f41caa3627b0bae8).

@yanavlasov as the author. The [test itself](https://github.com/envoyproxy/envoy/blob/b048141c72d5f8299f6a6e904e38a85ba5ea8c33/test/integration/tcp_tunneling_integration_test.cc#L457-L458) also looks quite suspicious and racy
```
  // Send CONNECT request and immediately send some data without waiting for 200
  // response from Envoy.
```
given the failure case is an unexpected 200 response.
