### ISSUE TITLE
Envoy Overload Manager CPU Utilization monitor only supports cgroupv1

### ISSUE THREAD

**Issue by sfc-gh-mtatoczenko** [envoyproxy/envoy#39978]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Envoy Overload Manager CPU Utilization monitor only supports cgroupv1

*Description*:

I am attempting to use the overload_manager CPU utilization monitor as described here: https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#loadshedding-in-k8s-environment

I am seeing these errors in my pod:
```shell
[2025-06-20 22:22:10.320][22][error][misc] [source/extensions/resource_monitors/cpu_utilization/linux_cpu_stats_reader.cc:67] Can't open linux cpu allocated file /sys/fs/cgroup/cpu/cpu.shares
[2025-06-20 22:22:10.320][22][info][main] [source/server/overload_manager_impl.cc:754] Failed to update resource envoy.resource_monitors.cpu_utilization: Can't open file to read CPU utilization
```

In reading through some information, the files there are for cgroupV1, whereas my pod is using cgroupv2. This means I cannot use the CONTAINER mode for CPU utilization metrics.

*Repro steps*:
- K8S version: 1.30.7
- Cloud provider: Azure
- Envoy version: v1.34.0

Output of my file system showing that it uses cgroupv2:
```shell
ls /sys/fs/cgroup/
cgroup.controllers
cgroup.events
cgroup.freeze
cgroup.kill
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cgroup.type
cpu.idle
cpu.max
...
```

*Admin and Stats Output*:
Not necessary

*Config*:
>Include the config used to configure Envoy.
Not entirely necessary

*Logs*:
>Include the access logs and the Envoy logs.
Main error:
```shell
[2025-06-20 22:39:25.595][22][error][misc] [source/extensions/resource_monitors/cpu_utilization/linux_cpu_stats_reader.cc:67] Can't open linux cpu allocated file /sys/fs/cgroup/cpu/cpu.shares
[2025-06-20 22:39:25.595][22][info][main] [source/server/overload_manager_impl.cc:754] Failed to update resource envoy.resource_monitors.cpu_utilization: Can't open file to read CPU utilization
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by frittentheke** [comment]
@sfc-gh-mtatoczenko  is this not a duplicate of https://github.com/envoyproxy/envoy/issues/39978 and recently fixed with https://github.com/envoyproxy/envoy/pull/42014 ?

**Comment by willianpaixao** [comment]
Hey @frittentheke @sfc-gh-mtatoczenko,
I think this issue was fixed by https://github.com/envoyproxy/envoy/pull/42014.
Can you double-check to see if we can close or whether there's anything left to implement?

**Comment by frittentheke** [comment]
@willianpaixao  I just tested Istio 1.30.1 via

```
[...]

        "resource_monitors": [                                                                                                                                                                                     
          {                                                                                                                                                                                                        
            "name": "envoy.resource_monitors.cpu_utilization",                                                                                                                                                     
            "typed_config": {                                                                                                                                                                                      
              "@type": "type.googleapis.com/envoy.extensions.resource_monitors.cpu_utilization.v3.CpuUtilizationConfig",                                                                                           
              "mode": "CONTAINER"                                                                                                                                                                                  
            }                                                                                                                                                                                                      
          }                                                                                                                                                                                                        
        ]   


[...]
```


And it works fine!

**Comment by willianpaixao** [comment]
Awesome! So we can close this issue? cc @sfc-gh-mtatoczenko

**Comment by wdauchy** [comment]
I think this is not fully fixed. cgroup v2 CONTAINER mode still fails at startup on a common Kubernetes setup.

`CpuPaths::isV2()` requires all three of `cpu.stat`, `cpu.max`, and `cpuset.cpus.effective` under `/sys/fs/cgroup`, and `LinuxContainerCpuStatsReader::create()` reads `/sys/fs/cgroup/cpu.max` directly. This assumes `/sys/fs/cgroup` is the container's own leaf cgroup. When the container runs in the host cgroup namespace (a common container runtime setup), `/sys/fs/cgroup` is the cgroup v2 root instead. `cpu.stat` and `cpuset.cpus.effective` exist at the root, but `cpu.max` does not, because the kernel never creates `cpu.max` at a cgroup v2 root. So `isV2()` fails on the missing `cpu.max`, `isV1()` is false on a v2-only host, and `create()` fails config init, which aborts startup.

I confirmed this on an affected node: at `/sys/fs/cgroup` (the host root) `cpu.stat` and `cpuset.cpus.effective` are present and `cpu.max` is absent. The pod's real leaf cgroup from `/proc/self/cgroup` has all three, with `cpu.max` = `max 100000` (no quota).

For reference: #42014 added this detection, #43957 works around the same strictness in tests by catching the exception, and #47056 turned the throw into an equally fatal status. The root cause is still present on main.

Proposed fix, two parts:
1. The proper fix is to resolve the container cgroup from `/proc/self/cgroup` instead of assuming `/sys/fs/cgroup` is the leaf, so detection reads the correct files.
2. At minimum, degrade gracefully: detect v2 from `cpu.stat`, treat a missing or `max` `cpu.max` as no CPU limit (fall back to online CPU count), and never fail config init for this optional monitor. Happy to open a PR.
