### ISSUE TITLE
libevent replacement with libev

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#4952]
libev has a few advantages over libevent:
* It scales better (see http://libev.schmorp.de/bench.html), which could come into play for handling very large numbers of connections (unlikely to make a difference for other situations).
* It supports better loop instrumentation and interception via check/prepare/idle watchers. This is actually my current motivation; I would like to instrument the loop duration and delay, generating histograms - libevent doesn't support this today based on my evaluation.
* We can avoid taking a pthread lock during the event loop.

Downsides include:
* We still need evbuffer support, so will need to link against both libev and libevent.
* We are perturbing a core part of the Envoy I/O model. This might have stability and performance implications (hopefully for the better..).
* We would need to more I/O outselves, e.g. replacing uses of `evconnlistener`.

Open questions:
* Should we also evaluate and consider https://github.com/libuv/libuv? 
* What about Windows support? Apparently IOCP doesn't work great in libev (or libevent), https://stackoverflow.com/questions/8042796/libev-on-windows says it is `select` based.

CC @sesmith177 @tonya11en @mattklein123 @envoyproxy/maintainers

**Comment by mattklein123** [comment]
Makes sense to me to investigate, though I am definitely concerned about the regression risk. If we go down this rode, I would recommend doing this incrementally, for example by starting with getting rid of evconnlistener usage (should be easy).

> What about Windows support?

IIRC right now on Windows we are using the BSD socket compat APIs so IOCP doesn't matter very much (since we now do manual buffer operations). In the future if perf on Windows matters I think we would likely develop a dedicated IOCP based transport socket?

**Comment by ggreenway** [comment]
In a previous project I worked on, I found that libev had some serious problems on mac, and was barely usable for windows. 

I also used libuv. It had much better cross-platform support, but the IO model treats everything as IOCP. This makes windows support work really well, but it meant a lot of code changes to accommodate that.

Note that my experience with both of these is from 5 years ago, so things may have changed.

**Comment by htuch** [comment]
@ggreenway I think libev has not changed much in several years. Neither has libevent. Most of the active development these days is on libuv due to the NodeJS dependency.

My understanding is that libuv started life as a common frontend for libev (on POSIX) and IOCP (Windows). As a result, if we port to either libev or libuv, I think adding the other shouldn't be too hard. For example, libuv also has the idle/prepare/check watcher model in its event loop.

So, my current thinking is to make it easy enough that we can support libev or libuv as a build time or CLI option, and we can evaluate how well these EVs end up working in practice on the platforms we support.

**Comment by ggreenway** [comment]
I'm digging deep into my memory, but here's my recollection:

IO readiness (kqueue/epoll) can be emulated in terms of an IOCP-based API, but IOCP cannot be emulated in terms of a readiness-based API. So libuv uses an IOCP-style API, which looks much different from normal BSD-sockets. All socket operations can be async, and have a completion callback. This has effects on the lifetime of various objects.

I ported some software from libev to libuv (to add "good" windows support). It was a large undertaking. The APIs were not similar enough to make supporting both at the same time attractive.

**Comment by conqerAtapple** [comment]
Having recently ported our libev based framework to libUV, some of the advantages are:

- portability
- better API
- good support for timers, signals etc

One thing I found a bit annoying was that the API doesn’t expose read and write ready events separately. 


-Jojy

**Comment by sesmith177** [comment]
@htuch Right now, our fork does not have any significant changes from the current Envoy event loop.  This causes an issue because Envoy expects edge-triggered behavior, but libevent on Windows only supports level-triggering. This causes the write-ready callbacks to trigger every time through the event loop, wasting a whole bunch of CPU. There is not an issue on the read side, since we always read all the data that's available. 

If we correctly understand how http://docs.libuv.org/en/v1.x/poll.html works (having never used the library) it appears to be level-triggered? In that case, the changes required to make this work on Linux/OSX would probably also help out on Windows, since now the event loop would trigger in the same manner on both.

So, we don't have any special attachment to libevent and think that switching to libuv should be fine. While it may be the case that IOCP are required in the future, we have not made it to that point yet.

BTW, we do not work at Microsoft, we are from Pivotal.

**Comment by htuch** [comment]
@sesmith177 can you share your complete WiP again in some PR? Will https://github.com/envoyproxy/envoy/pull/4970 break you? I'd like to understand how SOCKET and the listen/accept/descriptor watch all interoperate on Windows in your port.

**Comment by sesmith177** [comment]
Here's our current WIP: https://github.com/greenhouse-org/envoy/tree/windows-linux-build

We don't think #4970 would break us. Currently, we use `typedef` to handle the `int` / `SOCKET` difference, though that will probably change by the time we get it upstream (see #4828)

**Comment by sesmith177** [comment]
@htuch we'll give it a look -- hopefully we end up in the "much easier/better" bucket

**Comment by sbelair2** [comment]
@htuch The Envoy interface to VPP will be through a library we will link into Envoy, called VCL. VCL allows the clients (Envoy here) to set up an epoll loop for events from VPP. So libuv should be fine for that interface since it supports poll.

**Comment by sbelair2** [comment]
@htuch VCL only supports edge-triggered notifications. Also, VCL has its own poll implementation, so if there are kernel fds and vpp fds we might have to support nested epolls, or something like that. Not optimal, but not entirely sure- I'll look into it more soon.

**Comment by sesmith177** [comment]
@htuch we've had a chance to take a look at libuv on Windows (specifically `uv_stream_t` and `uv_fs_event_t`). 

It does appear that using libuv will fix the problem of write events constantly triggering on Windows. We were able to verify this by hacking together a version of the dispatcher that wrapped libuv instead of libevent. That said, we didn't go as far as integrating this dispatcher with the rest of Envoy -- as mentioned above, that would require a significant amount of work.

It looks like it will simplify the file-watching issues -- our Windows implementation will not have to work around the fact that libevent can only handles sockets on Windows. It also makes it possible to have one implementation of the WatcherImpl class instead of 3.

If it is decided that moving off libevent is the way to go, we would definitely like to help move it forward

**Comment by htuch** [comment]
@sesmith177 ack, thanks for digging into this. I actually asked Vaclav at https://envoyconna18.sched.com/event/HDdl/using-envoy-for-data-aware-traffic-routing-in-azure-service-fabric-vaclav-turecek-microsoft about this from the MSFT perspective. Their thoughts were that they had made use of libuv internally in various other places, whether it makes sense for Envoy comes down to how hard IOCP is vs. standalone IOCP in a transport socket.

I think we should keep this open in case someone has bandwidth to dig further; we have plans to hack libevent for the measurement aspects that originally motivated for now.

**Comment by brian-pane** [comment]
Related to this, I've started working on a buffer implementation that eliminates the need for evbuffer. (It looks sort of like Folly's IOBuf, but without the reference-counting.) I hope to have a PR ready for review by the end of the month.

**Comment by brian-pane** [comment]
> Related to this, I've started working on a buffer implementation that eliminates the need for evbuffer. (It looks sort of like Folly's IOBuf, but without the reference-counting.) I hope to have a PR ready for review by the end of the month.

Update: I'm still working on a new buffer implementation, but it is taking longer than I expected. It turns out that there's a lot of code in both Envoy and the test suite that assumes the data in a `Buffer::Instance` will be split into slices in exactly the way that evbuffer does it.

**Comment by davidfowl** [comment]
I don't know the envoy codebase at all but I've worked on one of those codebases at MSFT (on ASP.NET Core's Kestrel webserver), if you have any more specific questions or general questions, me or @halter73 would be happy to answer (of course the devil is in the details).

**Comment by htuch** [comment]
@davidfowl @halter73 the crux of the current discussion is whether we would see appreciable benefits to the Windows port to justify switching to `libuv`. There is a feeling that this switch might destabilize a core part of Envoy's event loop and I/O scheduling, which we might be willing to take on if we get a long term improvement. @sesmith177 has some discussion here above, looking at the IOCP future for the Windows port would be the most valuable at this point.

**Comment by halter73** [comment]
libuv's event loop doesn't make it easy to implement an APIs need to be accessed from arbitrary threads. libuv APIs with the exception of uv_send must all be called from a single thread and all libuv events are fired from that same thread.

The main thing this means for Kestrel is that it never runs user code on the libuv event loop. Kestrel has to do a fair amount of marshaling and dispatching back-and-forth to prevent user code from ruining I/O performance or blocking I/O entirely.

This limitation is far more constraining than using IOCP directly. With IOCP, you can invoke WSASend/Recv from arbitrary threads, and it can be configured to skip IOCP for immediate success on said arbitrary thread. You can also configure multiple I/O threads to service a single port.

Since doing all I/O on a single thread isn't acceptable for I/O-heavy applications, Kestrel runs multiple event loops. To balance load across the event loops, Kestrel listens for new connections on a primary event loop and then round-robin dispatches each connection to the event loop that will handle all of its subsequent I/O. This likely is less fair than using a single IOCP which would give FIFO I/O completion across all the dequeuing threads.

libuv makes even this limited form I/O multithreading tricky. The only supported to hand off a connection to another event loop is to pass socket descriptors over a pipe. The upside is that this mechanism works even across process boundaries, but it's not without issues. To prevent this from putting the socket into a slower emulated IOCP mode on Windows, Kestrel has to [manually call NtSetInformationFile](https://github.com/aspnet/AspNetCore/blob/17c6a64997807e92cf53b42dc5ecb5a2a46bcb08/src/Servers/Kestrel/Transport.Libuv/src/Internal/ListenerPrimary.cs#L140-L162) to detach the socket's IOCP from the primary accept loop before the handoff.

If you're already happy with your event handling, scheduling, and socket handling in non-Windows environments, creating a custom IOCP-based transport socket seems like the way to go. IOCP isn't *that* difficult.

If you have a greenfield project that needs a cross-platform socket abstraction and you don't mind designing your project's I/O around libuv's event loop, libuv is a much more appealing choice.

**Comment by htuch** [comment]
@halter73 got it. FWIW, Envoy is perfectly good with all `libuv` APIs being called on the same thread, since we have a siloed design; each connection/request is pinned to a single worked thread and dispatch loop, we rarely do cross-thread stuff other than posting messages. From what you say, it seems we might still want to go down the path of a IOCP transport socket though, since we're not getting a huge win from `libuv` here.

**Comment by antoniovicente** [comment]
The lack of libevent APIs that allow us to instrument the start/end of an iteration should be fixed one way or another.  Step 1 may be to send a PR to our friends at libevent to add hooks before and after the call to evsel->dispatch(), and at the bottom of the loop at event_base_loop: https://github.com/libevent/libevent/blob/master/event.c#L2025 .  The alternative is to go replace libevent.

The level trigger situation on Windows doesn't sound great.  There are some apparent performance issues with use of readDisable in linux to tweak fd masks when we want to stop reading that may motivate us to rely more on edge trigger behavior for reads in the future at least when read/write limits are enabled.

**Comment by htuch** [comment]
@antoniovicente @mergeconflict added prepare/watch-like support in https://github.com/libevent/libevent/pull/793. Is this sufficient for what you want to do or are there new hooks needed?

**Comment by nigriMSFT** [comment]
On the Windows side, libevent was recently given a much more scalable backend https://github.com/libevent/libevent/pull/1006 on Windows. This should ease at least some concerns regarding libevent scalability on Windows. Edge-triggering is still not supported though.

**Comment by mattklein123** [comment]
Thanks @nigriMSFT. Note I also just discussed this topic with @davinci26 who you might work with?

From Microsoft's perspective, should we assume that one way or the other we will make libevent work well on Windows? I think my overall preference would be to stay on libevent and do tactical fixes versus switching event loops unless there is a super compelling reason. cc @antoniovicente @alyssawilk

**Comment by nigriMSFT** [comment]
@mattklein123 yes we work together and yes I think that is a reasonable assumption

**Comment by daixiang0** [comment]
What about the process of replacement now? I do not find final conclusion here.

**Comment by antoniovicente** [comment]
I think this issue should be closed.  We are not considering moving away from libevent at this time.
